project:
  type: website
  output-dir: docs

website:
  title: "Riley Rudd"
  navbar:
    right:
      - text: Blogs
      - href: blog.qmd
      - icon: github
        href: https://github.com/rileyrudd
      - text: Articles
        menu: 
          - All posts
          - Machine Learning
      - icon: Linkedin
        href: "https://www.linkedin.com/in/riley-rudd-1166a3192/"

format:
  html:
    theme: journal
    css: styles.css

editor: visual